--- #YAML:1.0
name:                re-engine-Plan9
version:             0.15
abstract:            Plan 9 regular expression engine
license:             perl
author:              
    - Ævar Arnfjörð Bjarmason <avar@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
